# Driver principal
webdriver.driver=chrome

# CLAVE para Demoblaze (alerts JS no deterministas)
webdriver.unhandledPromptBehavior=ignore

# Opcional pero útil para ejecuciones headless
serenity.take.screenshots=AFTER_EACH_STEP