sonar.projectKey=WMOLINAV_demoblaze-serenity-automation
sonar.organization=wmolinav
sonar.host.url=https://sonarcloud.io

sonar.sources=src/test/java
sonar.tests=src/test/java
sonar.java.binaries=target/test-classes
sonar.java.test.binaries=target/test-classes

sonar.sourceEncoding=UTF-8
