sonar.projectKey=WMOLINAV_demoblaze-serenity-automation
sonar.organization=wmolinav

# Código de pruebas
sonar.sources=src/test/java
sonar.tests=src/test/java

# Binarios de pruebas (CLAVE)
sonar.java.binaries=target/test-classes
sonar.java.test.binaries=target/test-classes

sonar.sourceEncoding=UTF-8
